// uploadFile.js
const axios = require("axios");
const fs = require("fs");
const FormData = require("form-data");
const denoServerUrl = "http://127.0.0.1:8000/api/v1";
const transcodeUrl=denoServerUrl+"/transcode/uploadSegment"
/**
 * Upload a file to the server.
 * @param {string} filePath - The path of the file to upload.
 * @param {string} fileName - The name of the file to be uploaded.
 * @param {string} accessToken - The access token for authorization.
 */
const uploadFile = (filePath, fileName, accessToken) => {
    console.log("uploading")
  // Create a form-data instance
  const formData = new FormData();
  
  // Read the file as a stream
  const fileStream = fs.createReadStream(filePath);
  
  // Append the file stream to the form-data instance
  formData.append("file", fileStream, fileName);

  // Perform the file upload using Axios
  axios
    .post(transcodeUrl, formData, {
      headers: {
        "Content-Type": "multipart/form-data",
        Authorization: `Bearer ${accessToken}`,
        ...formData.getHeaders(), // Add headers generated by form-data
      },
    })
    .then(() => {
      console.log(`Successfully uploaded file: ${fileName}`);
    })
    .catch((error) => {
      console.log(`Error uploading segment: ${error.message}`);
    });
};

module.exports = uploadFile;
